# Site settings
author: Laura Travin
title: This blog can fail, it is code.
header-img: img/home-bg.png
email: laura.travin@gmail.com
copyright_name: Laura Travin
description: > # this means to ignore newlines until "baseurl:"
  Survival notes: keep motivation in coding.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lauratravin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
